# Generated by Django 5.2.13 on 2026-05-01 14:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0298_pluggable_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembundle',
            name='designated_price_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddConstraint(
            model_name='itembundle',
            constraint=models.CheckConstraint(condition=models.Q(('designated_price', Decimal('0.00')), ('designated_price_percent', Decimal('0.00')), _connector='OR'), name='itembundle_designated_price_one_of'),
        ),
    ]
