# Generated by Django 5.2.12 on 2026-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0306_alter_eventmetaproperty_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='valid_if_pending',
            field=models.BooleanField(default=False),
        ),
    ]
