# Generated by Django 5.2.17 on 2026-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("efcc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="installmentplan",
            name="mode",
            field=models.CharField(default="pull", max_length=10),
        ),
        migrations.AddField(
            model_name="scheduledinstallment",
            name="overdue_notice_sent",
            field=models.BooleanField(default=False),
        ),
    ]
